/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestione.magazzinogui;

import java.awt.Toolkit;

/**
 *
 * Questa classe contiene l'interfaccia grafica (GUI) per la gestione del
 * Database.
 *
 * @author Nino Zullo
 * @since 22/01/24
 * @version 1.0.0 - Beta
 *
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuGUI
     */
    Metodi m;

    /**
     * Imposta l'icona della finestra e il titolo. L'icona viene caricata dal
     * percorso relativo "/Icona.png". Il titolo della finestra viene impostato
     * su "Gestione Magazzino GUI".
     */
    private void ImpostaIcona() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icona.png")));
        setTitle("Gestione Magazzino GUI");
    }

    /**
     * Inizializza l'istanza della classe Metodi. Questo metodo deve essere
     * chiamato per avviare le funzionalità della classe.
     */
    private void AvviaClasse() {
        m = new Metodi();
    }

    /**
     * Costruttore
     */
    public MainMenuGUI() {
        initComponents();
        this.AvviaClasse();
        m.popolaComboBoxFornitori(cmbNomeForn);
        ImpostaIcona();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        lblSfondoLaterale1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMainMenu = new javax.swing.JPanel();
        btnInserisci = new javax.swing.JButton();
        btnMostraGiacenza = new javax.swing.JButton();
        btnEsci = new javax.swing.JButton();
        lblBenvenuto = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSfondoLaterale = new javax.swing.JLabel();
        pnlMain = new javax.swing.JTabbedPane();
        pnlHomePage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblSf = new javax.swing.JLabel();
        pnlInserisciProdotti = new javax.swing.JPanel();
        chbVisualizzaCodProdotto = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPrezzo = new javax.swing.JTextField();
        lblCodForno = new javax.swing.JLabel();
        lblPrezzo = new javax.swing.JLabel();
        lblCodProd = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        cmbNomeForn = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnInserisciProdotti = new javax.swing.JButton();
        lblSfondoProd = new javax.swing.JLabel();
        pnlInserisciMovimenti = new javax.swing.JPanel();
        pnlZonaCentrale = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spnData = new javax.swing.JSpinner();
        txtIcona = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantità = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCodProdM = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlZonaBassa = new javax.swing.JPanel();
        chbMostraID = new javax.swing.JCheckBox();
        btnAggiungiSpostamento = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();
        pnlInserisciFornitori = new javax.swing.JPanel();
        txtNomeF = new javax.swing.JTextField();
        lblNomeF = new javax.swing.JLabel();
        txtCittàF = new javax.swing.JTextField();
        lblCittàF = new javax.swing.JLabel();
        lblCodForn = new javax.swing.JLabel();
        txtCodFornF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnlSotto = new javax.swing.JPanel();
        btnInserisciFornitori = new javax.swing.JButton();
        cmbCodForn = new javax.swing.JCheckBox();
        btnHome2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pnlGIacenza = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCerca = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtNomeProdottoG = new javax.swing.JTextField();
        btnMostra = new javax.swing.JButton();
        btnPulisci = new javax.swing.JButton();
        btnHome3 = new javax.swing.JButton();
        pnlInserisci = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        cmbSelezionaDB = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblSfondoLaterale1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/SfondoLaterale.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainMenu.setLayout(null);

        btnInserisci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Aggiungi.png"))); // NOI18N
        btnInserisci.setContentAreaFilled(false);
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnInserisci);
        btnInserisci.setBounds(40, 80, 80, 70);

        btnMostraGiacenza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/searching-data-in-database.png"))); // NOI18N
        btnMostraGiacenza.setContentAreaFilled(false);
        btnMostraGiacenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraGiacenzaActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnMostraGiacenza);
        btnMostraGiacenza.setBounds(50, 190, 70, 71);

        btnEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/esci.png"))); // NOI18N
        btnEsci.setBorderPainted(false);
        btnEsci.setContentAreaFilled(false);
        btnEsci.setDefaultCapable(false);
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnEsci);
        btnEsci.setBounds(30, 290, 80, 90);

        lblBenvenuto.setForeground(new java.awt.Color(0, 0, 0));
        lblBenvenuto.setText("Benvenuto");
        pnlMainMenu.add(lblBenvenuto);
        lblBenvenuto.setBounds(20, 20, 80, 16);

        lblNome.setBackground(new java.awt.Color(0, 0, 0));
        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Root");
        pnlMainMenu.add(lblNome);
        lblNome.setBounds(20, 40, 90, 20);

        lblSfondoLaterale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/SfondoLaterale.jpg"))); // NOI18N
        pnlMainMenu.add(lblSfondoLaterale);
        lblSfondoLaterale.setBounds(0, 0, 160, 400);

        pnlHomePage.setBackground(new java.awt.Color(255, 255, 255));
        pnlHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestione Prodotti - Menù ");
        pnlHomePage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, -1));

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Fai la tua Scelta nel menù laterale a sinistra!");
        pnlHomePage.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 560, 40));

        lblSf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Main.png"))); // NOI18N
        pnlHomePage.add(lblSf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        pnlMain.addTab("PaginaPrincipale", pnlHomePage);

        pnlInserisciProdotti.setBackground(new java.awt.Color(70, 161, 194));
        pnlInserisciProdotti.setLayout(null);

        chbVisualizzaCodProdotto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chbVisualizzaCodProdotto.setForeground(new java.awt.Color(255, 255, 255));
        chbVisualizzaCodProdotto.setText("Visualizza CodProdotto");
        chbVisualizzaCodProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbVisualizzaCodProdottoActionPerformed(evt);
            }
        });
        pnlInserisciProdotti.add(chbVisualizzaCodProdotto);
        chbVisualizzaCodProdotto.setBounds(250, 360, 190, 24);

        jPanel7.setBackground(new java.awt.Color(159, 244, 254));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nome");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));
        jPanel7.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 30));
        jPanel7.add(txtPrezzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, 30));

        lblCodForno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCodForno.setForeground(new java.awt.Color(0, 0, 0));
        lblCodForno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodForno.setText("CodForn");
        jPanel7.add(lblCodForno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, 30));

        lblPrezzo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrezzo.setForeground(new java.awt.Color(0, 0, 0));
        lblPrezzo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrezzo.setText("Prezzo");
        jPanel7.add(lblPrezzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 30));

        lblCodProd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCodProd.setForeground(new java.awt.Color(0, 0, 0));
        lblCodProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodProd.setText("CodProd");
        jPanel7.add(lblCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 30));
        lblCodProd.setVisible(false);
        jPanel7.add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 100, 30));
        txtCodProd.setVisible(false);

        cmbNomeForn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cmbNomeForn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aggiungi Prodotti");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 40));

        pnlInserisciProdotti.add(jPanel7);
        jPanel7.setBounds(0, 0, 560, 140);

        btnInserisciProdotti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Aggiungi.png"))); // NOI18N
        btnInserisciProdotti.setBorderPainted(false);
        btnInserisciProdotti.setContentAreaFilled(false);
        btnInserisciProdotti.setDefaultCapable(false);
        btnInserisciProdotti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciProdottiActionPerformed(evt);
            }
        });
        pnlInserisciProdotti.add(btnInserisciProdotti);
        btnInserisciProdotti.setBounds(40, 330, 56, 57);

        lblSfondoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Prodotti1.png"))); // NOI18N
        pnlInserisciProdotti.add(lblSfondoProd);
        lblSfondoProd.setBounds(0, 140, 560, 210);

        pnlMain.addTab("InserisciProdotti", pnlInserisciProdotti);

        pnlInserisciMovimenti.setLayout(null);

        pnlZonaCentrale.setBackground(new java.awt.Color(255, 255, 255));
        pnlZonaCentrale.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data");
        pnlZonaCentrale.add(jLabel1);
        jLabel1.setBounds(0, 50, 58, 25);

        spnData.setModel(new javax.swing.SpinnerDateModel());
        spnData.setEditor(new javax.swing.JSpinner.DateEditor(spnData, "yyyy-MM-dd"));
        pnlZonaCentrale.add(spnData);
        spnData.setBounds(60, 50, 130, 30);

        txtIcona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/movimenti.jpg"))); // NOI18N
        pnlZonaCentrale.add(txtIcona);
        txtIcona.setBounds(110, 80, 400, 270);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleziona", "Carico", "Scarico" }));
        pnlZonaCentrale.add(cmbTipo);
        cmbTipo.setBounds(440, 50, 100, 26);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo");
        pnlZonaCentrale.add(jLabel6);
        jLabel6.setBounds(380, 50, 58, 25);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Quantità");
        pnlZonaCentrale.add(jLabel8);
        jLabel8.setBounds(190, 50, 87, 30);
        pnlZonaCentrale.add(txtQuantità);
        txtQuantità.setBounds(290, 50, 90, 30);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CodProd");
        pnlZonaCentrale.add(jLabel9);
        jLabel9.setBounds(10, 130, 87, 25);
        pnlZonaCentrale.add(txtCodProdM);
        txtCodProdM.setBounds(10, 170, 90, 30);
        pnlZonaCentrale.add(txtID);
        txtID.setBounds(10, 260, 90, 30);
        txtID.setVisible(false);

        lblID.setBackground(new java.awt.Color(0, 0, 0));
        lblID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("ID");
        pnlZonaCentrale.add(lblID);
        lblID.setBounds(10, 230, 87, 25);
        lblID.setVisible(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Inserisci Movimenti");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlZonaCentrale.add(jLabel12);
        jLabel12.setBounds(0, 0, 560, 50);

        pnlInserisciMovimenti.add(pnlZonaCentrale);
        pnlZonaCentrale.setBounds(0, 0, 560, 340);

        pnlZonaBassa.setBackground(new java.awt.Color(221, 231, 245));

        chbMostraID.setText("Mostra ID");
        chbMostraID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMostraIDActionPerformed(evt);
            }
        });

        btnAggiungiSpostamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Aggiungi.png"))); // NOI18N
        btnAggiungiSpostamento.setBorderPainted(false);
        btnAggiungiSpostamento.setContentAreaFilled(false);
        btnAggiungiSpostamento.setDefaultCapable(false);
        btnAggiungiSpostamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiSpostamentoActionPerformed(evt);
            }
        });

        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Home.png"))); // NOI18N
        btnHome1.setBorderPainted(false);
        btnHome1.setContentAreaFilled(false);
        btnHome1.setDefaultCapable(false);
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlZonaBassaLayout = new javax.swing.GroupLayout(pnlZonaBassa);
        pnlZonaBassa.setLayout(pnlZonaBassaLayout);
        pnlZonaBassaLayout.setHorizontalGroup(
            pnlZonaBassaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZonaBassaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAggiungiSpostamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(chbMostraID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btnHome1)
                .addGap(22, 22, 22))
        );
        pnlZonaBassaLayout.setVerticalGroup(
            pnlZonaBassaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZonaBassaLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlZonaBassaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZonaBassaLayout.createSequentialGroup()
                        .addGroup(pnlZonaBassaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHome1)
                            .addComponent(btnAggiungiSpostamento))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZonaBassaLayout.createSequentialGroup()
                        .addComponent(chbMostraID)
                        .addGap(20, 20, 20))))
        );

        pnlInserisciMovimenti.add(pnlZonaBassa);
        pnlZonaBassa.setBounds(0, 330, 560, 80);

        pnlMain.addTab("InserisciMovimenti", pnlInserisciMovimenti);

        pnlInserisciFornitori.setBackground(new java.awt.Color(216, 249, 254));
        pnlInserisciFornitori.setLayout(null);
        pnlInserisciFornitori.add(txtNomeF);
        txtNomeF.setBounds(110, 80, 100, 30);

        lblNomeF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNomeF.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeF.setText("Nome");
        pnlInserisciFornitori.add(lblNomeF);
        lblNomeF.setBounds(10, 80, 100, 30);
        pnlInserisciFornitori.add(txtCittàF);
        txtCittàF.setBounds(400, 80, 100, 30);

        lblCittàF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCittàF.setForeground(new java.awt.Color(0, 0, 0));
        lblCittàF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCittàF.setText("Città");
        pnlInserisciFornitori.add(lblCittàF);
        lblCittàF.setBounds(300, 80, 100, 30);

        lblCodForn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCodForn.setForeground(new java.awt.Color(0, 0, 0));
        lblCodForn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodForn.setText("CodForn");
        pnlInserisciFornitori.add(lblCodForn);
        lblCodForn.setBounds(10, 130, 100, 30);
        lblCodForn.setVisible(false);

        txtCodFornF.setVisible(false);
        pnlInserisciFornitori.add(txtCodFornF);
        txtCodFornF.setBounds(110, 130, 100, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Fornitor.jpg"))); // NOI18N
        jLabel5.setText("lblSfondoFornitori");
        pnlInserisciFornitori.add(jLabel5);
        jLabel5.setBounds(0, 80, 560, 260);

        pnlSotto.setBackground(new java.awt.Color(71, 141, 153));

        btnInserisciFornitori.setIcon(new javax.swing.ImageIcon("C:\\Users\\nizu\\Documents\\NetBeansProjects\\Gestione MagazzinoGUI\\images\\Aggiungi.png")); // NOI18N
        btnInserisciFornitori.setBorderPainted(false);
        btnInserisciFornitori.setContentAreaFilled(false);
        btnInserisciFornitori.setDefaultCapable(false);
        btnInserisciFornitori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciFornitoriActionPerformed(evt);
            }
        });

        cmbCodForn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbCodForn.setForeground(new java.awt.Color(0, 0, 0));
        cmbCodForn.setText("Mostra CodForn");
        cmbCodForn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmbCodForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodFornActionPerformed(evt);
            }
        });

        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Home.png"))); // NOI18N
        btnHome2.setBorderPainted(false);
        btnHome2.setContentAreaFilled(false);
        btnHome2.setDefaultCapable(false);
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSottoLayout = new javax.swing.GroupLayout(pnlSotto);
        pnlSotto.setLayout(pnlSottoLayout);
        pnlSottoLayout.setHorizontalGroup(
            pnlSottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSottoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnInserisciFornitori)
                .addGap(110, 110, 110)
                .addComponent(cmbCodForn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnHome2)
                .addGap(30, 30, 30))
        );
        pnlSottoLayout.setVerticalGroup(
            pnlSottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSottoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlSottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome2)
                    .addGroup(pnlSottoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSottoLayout.createSequentialGroup()
                            .addComponent(btnInserisciFornitori)
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSottoLayout.createSequentialGroup()
                            .addComponent(cmbCodForn)
                            .addGap(37, 37, 37)))))
        );

        pnlInserisciFornitori.add(pnlSotto);
        pnlSotto.setBounds(0, 310, 560, 100);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Inserisci Fornitore");
        pnlInserisciFornitori.add(jLabel13);
        jLabel13.setBounds(0, 20, 560, 40);

        pnlMain.addTab("InserisciFornitori", pnlInserisciFornitori);

        pnlGIacenza.setBackground(new java.awt.Color(203, 232, 240));
        pnlGIacenza.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/cerca.png"))); // NOI18N
        pnlGIacenza.add(jLabel7);
        jLabel7.setBounds(330, 100, 200, 178);

        tblCerca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCerca);

        pnlGIacenza.add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 260, 190);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nome Prodotto");
        pnlGIacenza.add(jLabel10);
        jLabel10.setBounds(30, 20, 190, 30);
        pnlGIacenza.add(txtNomeProdottoG);
        txtNomeProdottoG.setBounds(220, 20, 100, 30);

        btnMostra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/cerca2.png"))); // NOI18N
        btnMostra.setContentAreaFilled(false);
        btnMostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraActionPerformed(evt);
            }
        });
        pnlGIacenza.add(btnMostra);
        btnMostra.setBounds(360, 10, 139, 82);

        btnPulisci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/pulisci.png"))); // NOI18N
        btnPulisci.setContentAreaFilled(false);
        btnPulisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulisciActionPerformed(evt);
            }
        });
        pnlGIacenza.add(btnPulisci);
        btnPulisci.setBounds(140, 303, 56, 57);

        btnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Home.png"))); // NOI18N
        btnHome3.setBorderPainted(false);
        btnHome3.setContentAreaFilled(false);
        btnHome3.setDefaultCapable(false);
        btnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome3ActionPerformed(evt);
            }
        });
        pnlGIacenza.add(btnHome3);
        btnHome3.setBounds(420, 300, 56, 57);

        pnlMain.addTab("Mostra Giacenza", pnlGIacenza);

        pnlInserisci.setBackground(new java.awt.Color(255, 255, 255));
        pnlInserisci.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Conferma.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlInserisci.add(jButton1);
        jButton1.setBounds(240, 320, 50, 40);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Home.png"))); // NOI18N
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setDefaultCapable(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlInserisci.add(btnHome);
        btnHome.setBounds(450, 320, 56, 57);

        cmbSelezionaDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleziona", "Prodotti", "Fornitori", "Movimenti" }));
        pnlInserisci.add(cmbSelezionaDB);
        cmbSelezionaDB.setBounds(150, 20, 240, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/pulisci.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlInserisci.add(jButton3);
        jButton3.setBounds(60, 310, 56, 57);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestione/magazzinogui/Scegli.png"))); // NOI18N
        pnlInserisci.add(jLabel11);
        jLabel11.setBounds(130, 60, 300, 200);

        pnlMain.addTab("Inserisci", pnlInserisci);

        pnlMainMenu.add(pnlMain);
        pnlMain.setBounds(160, -70, 560, 470);

        getContentPane().add(pnlMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 718, 398));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        m.Esci();
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        m.VaiAdInserisci(pnlMain);
    }//GEN-LAST:event_btnInserisciActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        m.ResettaCheckbox(cmbSelezionaDB);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        m.TornaAllaHome(pnlMain);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        m.SelezionaDatabase(cmbSelezionaDB.getSelectedItem().toString(), pnlMain);
        cmbSelezionaDB.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbCodFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodFornActionPerformed
        m.MostraCodForn(cmbCodForn, lblCodForn, txtCodFornF);
    }//GEN-LAST:event_cmbCodFornActionPerformed

    private void btnInserisciFornitoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciFornitoriActionPerformed
        m.InserisciFornitori(txtNomeF, txtCittàF, cmbCodForn, txtCodFornF);
    }//GEN-LAST:event_btnInserisciFornitoriActionPerformed

    private void btnAggiungiSpostamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiSpostamentoActionPerformed
        m.InserisciMovimenti(spnData, txtQuantità, txtCodProdM, cmbTipo, txtID, chbMostraID);
    }//GEN-LAST:event_btnAggiungiSpostamentoActionPerformed

    private void chbMostraIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMostraIDActionPerformed
        m.MostraCasellaID(chbMostraID, txtID, lblID);
    }//GEN-LAST:event_chbMostraIDActionPerformed

    private void btnInserisciProdottiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciProdottiActionPerformed
        m.InserisciProdotto(txtCodProd, txtNome, txtPrezzo, cmbNomeForn, chbVisualizzaCodProdotto);
    }//GEN-LAST:event_btnInserisciProdottiActionPerformed

    private void chbVisualizzaCodProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbVisualizzaCodProdottoActionPerformed
        m.ControllaCheckbox(chbVisualizzaCodProdotto, lblCodProd, txtCodProd);
    }//GEN-LAST:event_chbVisualizzaCodProdottoActionPerformed

    private void btnMostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraActionPerformed
        m.MostraGiacenzaAttuale(txtNomeProdottoG, tblCerca);
    }//GEN-LAST:event_btnMostraActionPerformed

    private void btnPulisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulisciActionPerformed
        m.PulisciGiacenza(txtNomeProdottoG, tblCerca);
    }//GEN-LAST:event_btnPulisciActionPerformed

    private void btnMostraGiacenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraGiacenzaActionPerformed
        m.VaiAGiacenza(pnlMain);
    }//GEN-LAST:event_btnMostraGiacenzaActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        m.TornaAllaHome(pnlMain);
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        m.TornaAllaHome(pnlMain);
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome3ActionPerformed
        m.TornaAllaHome(pnlMain);
    }//GEN-LAST:event_btnHome3ActionPerformed

    /**
     * 
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungiSpostamento;
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnInserisci;
    private javax.swing.JButton btnInserisciFornitori;
    private javax.swing.JButton btnInserisciProdotti;
    private javax.swing.JButton btnMostra;
    private javax.swing.JButton btnMostraGiacenza;
    private javax.swing.JButton btnPulisci;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbMostraID;
    private javax.swing.JCheckBox chbVisualizzaCodProdotto;
    private javax.swing.JCheckBox cmbCodForn;
    private javax.swing.JComboBox<String> cmbNomeForn;
    private javax.swing.JComboBox<String> cmbSelezionaDB;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBenvenuto;
    private javax.swing.JLabel lblCittàF;
    private javax.swing.JLabel lblCodForn;
    private javax.swing.JLabel lblCodForno;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeF;
    private javax.swing.JLabel lblPrezzo;
    private javax.swing.JLabel lblSf;
    private javax.swing.JLabel lblSfondoLaterale;
    private javax.swing.JLabel lblSfondoLaterale1;
    private javax.swing.JLabel lblSfondoProd;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JPanel pnlGIacenza;
    private javax.swing.JPanel pnlHomePage;
    private javax.swing.JPanel pnlInserisci;
    private javax.swing.JPanel pnlInserisciFornitori;
    private javax.swing.JPanel pnlInserisciMovimenti;
    private javax.swing.JPanel pnlInserisciProdotti;
    private javax.swing.JTabbedPane pnlMain;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlSotto;
    private javax.swing.JPanel pnlZonaBassa;
    private javax.swing.JPanel pnlZonaCentrale;
    private javax.swing.JSpinner spnData;
    private javax.swing.JTable tblCerca;
    private javax.swing.JTextField txtCittàF;
    private javax.swing.JTextField txtCodFornF;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtCodProdM;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtIcona;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeF;
    private javax.swing.JTextField txtNomeProdottoG;
    private javax.swing.JTextField txtPrezzo;
    private javax.swing.JTextField txtQuantità;
    // End of variables declaration//GEN-END:variables
}
